language: python

python:
- "3.6"

before_install:
- sudo apt-get update

install:
- pip install -r requirements.txt

virtualenv:
  system_site_package: true

script:
- python -m unittest facial_recog/tests/test_app.py

